# yamllint disable-line rule:document-start
name: Devcontainer build

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'main'
    paths:
      - '.devcontainer'
      - '.github/workflows/devcontainer.yml'
  schedule:
    - cron: '30 3 1 * *'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.devcontainer'
      - '.github/workflows/devcontainer.yml'

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4
      -
        name: Lint shell script
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './.devcontainer'
      -
        name: Lint devcontainer.json
        run: |
          python3 -m pip install json-spec
          # TODO: Use submodule
          git clone https://github.com/devcontainers/spec/
          cd spec/schemas
          json validate --schema-file=devContainer.schema.json --document-file=../../.devcontainer/devcontainer.json

  devcontainer:
    runs-on: ubuntu-24.04
    needs:
      - lint
    timeout-minutes: 8
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4
      -
        name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli
      -
        name: Build the devcontainer
        run: devcontainer build --workspace-folder .
