name: Update Changelog

on:
  push:
    branches:
      - main
    paths:
      # Core content that should trigger changelog updates
      - 'src/**'
      - 'scripts/**'
      - 'haxinator-pigen-overlay/**'
      - 'docs/**/*.md'
      - 'README.md'
      - '!docs/changelog.md'  # Exclude changelog.md to prevent loops

jobs:
  update-changelog:
    # Skip if triggered by the bot itself
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 11  # Fetch 11 commits to ensure we get 10 for the log
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update changelog
        run: |
          # Get repository URL
          REPO_URL=$(git config --get remote.origin.url | sed 's/\.git$//' | sed 's/git@github.com:/https:\/\/github.com\//')
          
          # Create changelog content
          echo "---" > docs/changelog.md
          echo "title: Changelog" >> docs/changelog.md
          echo "nav_order: 8" >> docs/changelog.md
          echo "description: \"Recent changes in Haxinator 2000\"" >> docs/changelog.md
          echo "---" >> docs/changelog.md
          echo "" >> docs/changelog.md
          echo "# Recent Changes" >> docs/changelog.md
          echo "" >> docs/changelog.md
          echo "This page is automatically generated from the last 10 commits. " >> docs/changelog.md
          echo "[View full history on GitHub](${REPO_URL}/commits/main)." >> docs/changelog.md
          echo "" >> docs/changelog.md
          
          # Add the last 10 commits
          echo "## Commit History" >> docs/changelog.md
          echo "" >> docs/changelog.md
          
          # Process each commit individually to handle newlines properly
          git log -n 10 --format="### %ad - [%h](${REPO_URL}/commit/%H)%n%n%s%n%n%b" --date=short | while IFS= read -r line; do
            if [[ "$line" == *"\n"* ]]; then
              # First remove any existing bullet points, then add single bullet points
              processed_line=$(echo "$line" | sed 's/- \\n/\\n/g' | sed 's/\\n- /\\n/g' | sed 's/\\n/\n- /g')
              echo "$processed_line" >> docs/changelog.md
            else
              echo "$line" >> docs/changelog.md
            fi
          done

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet docs/changelog.md || echo "changes=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # Stage the changes
          git add docs/changelog.md
          git commit -m "docs: update changelog with recent commits"
          
          # Try to push changes, if fails, pull and rebase
          MAX_ATTEMPTS=3
          ATTEMPT=1
          
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT to push changes..."
            
            if git push; then
              echo "Successfully pushed changes"
              exit 0
            fi
            
            echo "Push failed, pulling latest changes..."
            git pull --rebase origin main
            
            ATTEMPT=$((ATTEMPT + 1))
          done
          
          echo "Failed to push changes after $MAX_ATTEMPTS attempts"
          exit 1 